import { RankedTester } from '@jsonforms/core';
import MaterialArrayControlRenderer from './MaterialArrayControlRenderer';
import MaterialObjectRenderer, { materialObjectControlTester } from './MaterialObjectRenderer';
import MaterialAllOfRenderer, { materialAllOfControlTester } from './MaterialAllOfRenderer';
import MaterialAnyOfRenderer, { materialAnyOfControlTester } from './MaterialAnyOfRenderer';
import MaterialOneOfRenderer, { materialOneOfControlTester } from './MaterialOneOfRenderer';
import MaterialEnumArrayRenderer, { materialEnumArrayRendererTester } from './MaterialEnumArrayRenderer';
export declare const materialArrayControlTester: RankedTester;
export { MaterialArrayControlRenderer };
export { MaterialObjectRenderer };
export { MaterialAllOfRenderer };
export { MaterialAnyOfRenderer };
export { MaterialOneOfRenderer };
export { MaterialEnumArrayRenderer };
export { materialObjectControlTester };
export { materialAllOfControlTester };
export { materialAnyOfControlTester };
export { materialOneOfControlTester };
export { materialEnumArrayRendererTester };
